### ISSUE TITLE
Using post-me with child website

### ISSUE THREAD

**Issue by Sharlaan** [alesgenova/post-me#54]
Hello,

Very nice project, i am wondering if can use post-me for this use-case :

- Say (for example) main page needs a css selector from another web site, opened in another tab
- According to the readme, post-me is able to communicate between tabs
- Is it possible to make some overlay above child website, prompting user to click on something on HTML, then the parent's click handler would return the event (and its target!)
- From the event parent's page would display what user clicked

Is this possible with post-me ? (browsers' security block me...)
If not, any idea ?

Thanks

**Comment by alesgenova** [comment]
Hi,
I'm not sure I understand all the questions, but I'll try to answer:

> 
> Very nice project, i am wondering if can use post-me for this use-case :
> 
>     * Say (for example) main page needs a css selector from another web site, opened in another tab
> 
>     * According to the readme, post-me is able to communicate between tabs
> 
Popup and tabs should work just like the iframe example from the docs. The difference would be the way you create the child window (`window.open()`?) and the way you access the parent window from the child (`window.opener` instead of `window.parent`).

>     * Is it possible to make some overlay above child website, prompting user to click on something on HTML, then the parent's click handler would return the event (and its target!)
> 
>     * From the event parent's page would display what user clicked
> 
> 
> Is this possible with post-me ? (browsers' security block me...)
> If not, any idea ?
> 
I don't quite understand the example, but due to browser limitations you wouldn't be able to pass dom nodes directly across contexts. But what you can easily do is listen for click events in your child app, and then re-emit a sanitized version of the event to the parent. Stripped down, the code might look like:

Parent:
```javascript
/* ... */
const connection = await ParentHandshake(messenger)
const remoteHandle = connection.remoteHandle();
remoteHandle.addEventListener('click', (e) => {
  console.log(e.clientX, e.clientY); // the click position or whatever prop.
});
```

Child:
```javascript
/* ... */
const btn1 = document.getElementById('btn1');
const btn2 = document.getElementById('btn2');
const connection = await ChildHandshake(messenger);
const localHandle = connection.localHandle();

const onClick = (e) => {
  const { clientX, clientY } = e;
  localHandle.emit('click', { clientX, clientY });
}

btn1.onclick = onClick;
btn2.onclick = onClick;
```

The other way around would work too (the parent emits events and the child listens to it).

If I didn't answer the question you originally had, feel free to elaborate on your example

**Comment by Sharlaan** [comment]
You got the idea i were thinking, but :
- i open the new tab with window.opener('https://external.url.com') from parent's code
- since i don't have "permissions" on child's code, i can't inject the click handler code in child's code to listen on user clicks
- i must do everything from parent's code only, is it possible ?

**Comment by alesgenova** [comment]
Got it, without having access to the child code, I can't think of a way you can achieve it, with post-me or any other library.
If you find a solution, I'd be curious to hear it!
